version = 0.1

[default.deploy.parameters]
stack_name = "web3-caveman-bff"
region = "us-east-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

s3_prefix = "web3-caveman-bff"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
